import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-providers";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Go Bimbingan Skripsi",
    description: "Generated by Fajar",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={font.className}>
              <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} storageKey="discord-theme">
                {children}
              </ThemeProvider>
              </body>
        </html>
    );
}


// "use client";

// import React from 'react';
// import Sidebar from '@/components/Sidebar';
// import './globals.css';

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <head>
//         {/* You can include meta tags, title, and other head elements here */}
//         <title>My Discord Clone</title>
//       </head>
//       <body className="flex h-screen bg-gray-900 text-white">
//         <Sidebar />
//         <main className="flex-grow">
//           {children}
//         </main>
//       </body>
//     </html>
//   );
// }